import json, re

SRC = "/Users/macos/ErgenTekstil/src/data/products.tr.json"

CAT_EN = {"Tayt": "Leggings", "Korse": "Shapewear", "Şort": "Shorts", "Genel": "General"}
CAT_AR = {"Tayt": "طماق", "Korse": "مشدّات", "Şort": "شورت", "Genel": "عام"}

COLOR_EN = {
    "Mavi": "Blue", "Kremit": "Terracotta", "Pembe": "Pink", "Kırmızı": "Red",
    "Siyah": "Black", "Turuncu": "Orange", "Yeşil": "Green", "Lacivert": "Navy",
    "Beyaz": "White", "Ten": "Nude",
}
COLOR_AR = {
    "Mavi": "أزرق", "Kremit": "طوبي", "Pembe": "وردي", "Kırmızı": "أحمر",
    "Siyah": "أسود", "Turuncu": "برتقالي", "Yeşil": "أخضر", "Lacivert": "كحلي",
    "Beyaz": "أبيض", "Ten": "بيج",
}

FEATURE_EN = {
    "% 20 Elastan": "20% Elastane",
    "% 82 Polyamid": "82% Polyamide",
    "%10 Elastan": "10% Elastane",
    "%15 Elastan": "15% Elastane",
    "%18 Elastan": "18% Elastane",
    "%20 Elastan": "20% Elastane",
    "%80 Polyamid": "80% Polyamide",
    "%82 Polyamid": "82% Polyamide",
    "%85 Bamboo": "85% Bamboo",
    "%90 Polyamid": "90% Polyamide",
    "%90 Polyamide": "90% Polyamide",
    "Ayarlanabilir ağraf": "Adjustable hook-and-eye closure",
    "Bölgesel duble etkili sekillendirme": "Targeted double-layer shaping",
    "Doğal bamboo kumaşıyla ipeksi dokunuş": "Silky touch with natural bamboo fabric",
    "Ekstra push-up özelliği": "Extra push-up effect",
    "Ekstra yüksek bel": "Extra high waist",
    "Günlük kullanıma uygun": "Suitable for everyday wear",
    "Kaymayı engelleyen slikon bant": "Non-slip silicone band",
    "Kaymayı Öneleyen silikon bant": "Non-slip silicone band",
    "Kaymayı önleyen silikon bant": "Non-slip silicone band",
    "Kaymayı önleyen silikon doku": "Non-slip silicone texture",
    "Kaymayı önleyen silikon serit": "Non-slip silicone strip",
    "Kaymayı önleyen silikon şerit": "Non-slip silicone strip",
    "Kaymayı önleyen silikon şerit1050": "Non-slip silicone strip",
    "Lacivert, Beyaz, Siyah renkler": "Available in Navy, White, Black",
    "Lacivert, Siyah ve Beyaz renkler": "Available in Navy, Black and White",
    "Micromasaj fonksiyonlu özel örme sistemi": "Special knit system with micro-massage function",
    "Nefes alabilen iç göstermez kumaş": "Breathable, opaque fabric",
    "Nefes alabilen kumaş": "Breathable fabric",
    "Push etkili": "Push-up effect",
    "Push-up etkisi": "Push-up effect",
    "Renk seçeneği; Natural": "Colour option: Natural",
    "S, M, L, XL": "S, M, L, XL",
    "S, M, L, XL ve XXL": "S, M, L, XL and XXL",
    "S, M, L, XL ve XXL beden seçenekleri": "S, M, L, XL and XXL size options",
    "S, M, L, XL, XXL ve 3XL": "S, M, L, XL, XXL and 3XL",
    "S, M, L, XL, XXL ve 3XL beden seçenekleri": "S, M, L, XL, XXL and 3XL size options",
    "S-M-L-XL": "S-M-L-XL",
    "S-M-L-XL-XXL": "S-M-L-XL-XXL",
    "Sezon renkler": "Seasonal colours",
    "Siyah renk": "Black colour",
    "Siyah ve Ten": "Black and Nude",
    "Siyah ve Ten rengi alternatifleri": "Black and Nude colour alternatives",
    "Siyah, Beyaz ve Ten": "Black, White and Nude",
    "Siyah, Beyaz ve Ten rengi alternatifleri": "Black, White and Nude colour alternatives",
    "Siyah, Beyaz ve Ten renkleri": "Black, White and Nude colours",
    "Siyah, Beyaz, Ten": "Black, White, Nude",
    "Sıklaştırıcı ve toparlayıcı etki": "Firming and shaping effect",
    "Ten /Beyaz / Siyah": "Nude / White / Black",
    "Ultra yüksek bel": "Ultra high waist",
    "Vücudu saran dikişsiz örgü sistemi": "Body-hugging seamless knit construction",
    "XS/S, M/L": "XS/S, M/L",
    "XS/S, M/L, L/XL": "XS/S, M/L, L/XL",
    "XS/S. M/L": "XS/S, M/L",
    "Yerli Üretim": "Made in Türkiye",
    "Yüksek bel extra sıkılaştırıcı korse": "High-waist extra firming shapewear",
    "yüksek bel": "high waist",
    "Çift taraflı silikon bant": "Double-sided silicone band",
    "Çıkarılabilir askı": "Removable straps",
    "İnce kumaşı sayesinde iz yapmaz.": "Thin fabric leaves no visible lines.",
    "İpeksi dokunuş": "Silky touch",
    "%100 Orijinal Ürün": "100% Original Product",
    "%30 Elastan": "30% Elastane",
    "%70 Polyamid": "70% Polyamide",
    "%82 Mikrofiber Polyamid": "82% Microfiber Polyamide",
    "%90 Bamboo": "90% Bamboo",
    "%90 Bamcoo": "90% Bamboo",
    "Beyaz ve Siyah renkleriyle": "In White and Black colours",
    "Bölgesel baskıyla duble etkili şekillenme": "Targeted-pressure double-layer shaping",
    "Bölgesel duble etki": "Targeted double-layer effect",
    "Bölgesel duble şekillendirici etki": "Targeted double-layer shaping effect",
    "Dolgun sünger": "Padded cups",
    "Doğal bamboo kumaş sayesinde ipeksi dokunuş": "Silky touch thanks to natural bamboo fabric",
    "Geliştirilmiş örgü sistemi": "Enhanced knit construction",
    "Göbeği kavrayan ergonomik kumaş": "Ergonomic fabric that contours the tummy",
    "Göbeği saran ergonomik örgü": "Ergonomic knit that wraps the tummy",
    "Kaymayı önleyen çevre silikon": "Non-slip silicone trim",
    "Kolay kullanılabilen kopça": "Easy-to-use hook closure",
    "Kolay kullanım": "Easy to use",
    "Kolay çıkarılabilen ağraf": "Easily removable hook-and-eye closure",
    "LAZER KESİM, Pamuk ağ": "LASER CUT, cotton gusset",
    "LAZER kesim, özel dikiş": "Laser cut, special stitching",
    "Lazer kesim, özel dikiş": "Laser cut, special stitching",
    "Nefes alabilen doğal bamboo kumaş": "Breathable natural bamboo fabric",
    "Nefes alabilen özel spor kumaş": "Breathable technical sports fabric",
    "Organik kumaş": "Organic fabric",
    "Organik, pratik kullanım": "Organic, practical to wear",
    "Pamuk ağ": "Cotton gusset",
    "Pamuk ağ, LAZER kesim iz yapmaz.": "Cotton gusset, laser-cut edges leave no visible lines.",
    "Push up etkili": "Push-up effect",
    "Rahat, konforu": "Comfortable fit",
    "Renk seçenekleri; Natural": "Colour options: Natural",
    "Renk; Siyah": "Colour: Black",
    "S, M, L": "S, M, L",
    "S, M, L, XL  beden seçenekleri": "S, M, L, XL size options",
    "S, M, L, XL ve XXL  beden seçenekleri": "S, M, L, XL and XXL size options",
    "S, M, L, XL, XXL  ve 3XL beden seçenekleri": "S, M, L, XL, XXL and 3XL size options",
    "S, M, L, XL, XXL ve 3XL  beden seçenekleri": "S, M, L, XL, XXL and 3XL size options",
    "S-M-L-XL-XXL-3XL": "S-M-L-XL-XXL-3XL",
    "S/M,  M/L,  L/XL  beden seçenekleri": "S/M, M/L, L/XL size options",
    "S/M, L/XL": "S/M, L/XL",
    "S/M, M/L, L/XL": "S/M, M/L, L/XL",
    "S/M, M/L. L/XL": "S/M, M/L, L/XL",
    "S/M. L/XL": "S/M, L/XL",
    "Sezon Renkleri ile": "With seasonal colours",
    "Sezon Renkleri İle": "With seasonal colours",
    "Siyah, Beyaz ve Ten renk alternatifi": "Black, White and Nude colour alternative",
    "Siyah, Beyaz, Ten ve sezon renkleriyle": "In Black, White, Nude and seasonal colours",
    "Siyah, Ekru ve Ten": "Black, Ecru and Nude",
    "Siyah, Ten": "Black, Nude",
    "Toparlatıcı ve şekillendirici etki": "Firming and shaping effect",
    "Toparlayıcı etki": "Shaping effect",
    "Vucudu sarar": "Hugs the body",
    "Vücudu saran korsajlı örgü": "Body-hugging corseted knit",
    "Vücudu saran organik kumaş": "Body-hugging organic fabric",
    "Vücudu sarar.": "Hugs the body.",
    "XS/S,  M/L": "XS/S, M/L",
    "XS/S,  M/L,  L/XL": "XS/S, M/L, L/XL",
    "Yok hissi, iz yapmaz.": "Weightless feel, leaves no visible lines.",
    "ipeksi dokunuş": "silky touch",
    "iz yapmaz.": "leaves no visible lines.",
    "pamuk ağ, iz yapmaz.": "cotton gusset, leaves no visible lines.",
    "vücudu sarar.": "hugs the body.",
    "Çıkarılabilen sünger": "Removable padding",
    "Özel korsajlı örgü": "Special corseted knit",
    "İpeksi bamboo kumaş": "Silky bamboo fabric",
    "İpeksi doku": "Silky texture",
    "İz yapmayan özel dikiş": "Special stitching that leaves no visible lines",
    "İz yapmaz.": "Leaves no visible lines.",
}

FEATURE_AR = {
    "% 20 Elastan": "20% إيلاستين",
    "% 82 Polyamid": "82% بولي أميد",
    "%10 Elastan": "10% إيلاستين",
    "%15 Elastan": "15% إيلاستين",
    "%18 Elastan": "18% إيلاستين",
    "%20 Elastan": "20% إيلاستين",
    "%80 Polyamid": "80% بولي أميد",
    "%82 Polyamid": "82% بولي أميد",
    "%85 Bamboo": "85% بامبو",
    "%90 Polyamid": "90% بولي أميد",
    "%90 Polyamide": "90% بولي أميد",
    "Ayarlanabilir ağraf": "إغلاق قابل للتعديل بالخطاف",
    "Bölgesel duble etkili sekillendirme": "تشكيل مضاعف موضعي",
    "Doğal bamboo kumaşıyla ipeksi dokunuş": "ملمس حريري بقماش البامبو الطبيعي",
    "Ekstra push-up özelliği": "تأثير رفع إضافي",
    "Ekstra yüksek bel": "خصر عالٍ جدًا",
    "Günlük kullanıma uygun": "مناسب للاستخدام اليومي",
    "Kaymayı engelleyen slikon bant": "شريط سيليكون مضاد للانزلاق",
    "Kaymayı Öneleyen silikon bant": "شريط سيليكون مضاد للانزلاق",
    "Kaymayı önleyen silikon bant": "شريط سيليكون مضاد للانزلاق",
    "Kaymayı önleyen silikon doku": "نسيج سيليكون مضاد للانزلاق",
    "Kaymayı önleyen silikon serit": "شريط سيليكون مضاد للانزلاق",
    "Kaymayı önleyen silikon şerit": "شريط سيليكون مضاد للانزلاق",
    "Kaymayı önleyen silikon şerit1050": "شريط سيليكون مضاد للانزلاق",
    "Lacivert, Beyaz, Siyah renkler": "متوفر بألوان كحلي وأبيض وأسود",
    "Lacivert, Siyah ve Beyaz renkler": "متوفر بألوان كحلي وأسود وأبيض",
    "Micromasaj fonksiyonlu özel örme sistemi": "نظام حياكة خاص بوظيفة تدليك دقيق",
    "Nefes alabilen iç göstermez kumaş": "قماش قابل للتنفس ولا يظهر من تحت الملابس",
    "Nefes alabilen kumaş": "قماش قابل للتنفس",
    "Push etkili": "تأثير رافع",
    "Push-up etkisi": "تأثير رافع",
    "Renk seçeneği; Natural": "خيار اللون: طبيعي",
    "S, M, L, XL": "S, M, L, XL",
    "S, M, L, XL ve XXL": "S, M, L, XL و XXL",
    "S, M, L, XL ve XXL beden seçenekleri": "مقاسات S, M, L, XL و XXL",
    "S, M, L, XL, XXL ve 3XL": "S, M, L, XL, XXL و 3XL",
    "S, M, L, XL, XXL ve 3XL beden seçenekleri": "مقاسات S, M, L, XL, XXL و 3XL",
    "S-M-L-XL": "S-M-L-XL",
    "S-M-L-XL-XXL": "S-M-L-XL-XXL",
    "Sezon renkler": "ألوان موسمية",
    "Siyah renk": "لون أسود",
    "Siyah ve Ten": "أسود وبيج",
    "Siyah ve Ten rengi alternatifleri": "بدائل الألوان الأسود والبيج",
    "Siyah, Beyaz ve Ten": "أسود وأبيض وبيج",
    "Siyah, Beyaz ve Ten rengi alternatifleri": "بدائل الألوان الأسود والأبيض والبيج",
    "Siyah, Beyaz ve Ten renkleri": "ألوان أسود وأبيض وبيج",
    "Siyah, Beyaz, Ten": "أسود، أبيض، بيج",
    "Sıklaştırıcı ve toparlayıcı etki": "تأثير مشدّ وموحّد للجسم",
    "Ten /Beyaz / Siyah": "بيج / أبيض / أسود",
    "Ultra yüksek bel": "خصر عالٍ للغاية",
    "Vücudu saran dikişsiz örgü sistemi": "نظام حياكة بلا خياطة يحتضن الجسم",
    "XS/S, M/L": "XS/S, M/L",
    "XS/S, M/L, L/XL": "XS/S, M/L, L/XL",
    "XS/S. M/L": "XS/S, M/L",
    "Yerli Üretim": "صناعة تركية",
    "Yüksek bel extra sıkılaştırıcı korse": "مشدّ بخصر عالٍ وتأثير شدّ إضافي",
    "yüksek bel": "خصر عالٍ",
    "Çift taraflı silikon bant": "شريط سيليكون مزدوج الجهة",
    "Çıkarılabilir askı": "حمالات قابلة للإزالة",
    "İnce kumaşı sayesinde iz yapmaz.": "قماشه الرقيق لا يترك أثرًا تحت الملابس.",
    "İpeksi dokunuş": "ملمس حريري",
    "%100 Orijinal Ürün": "منتج أصلي 100%",
    "%30 Elastan": "30% إيلاستين",
    "%70 Polyamid": "70% بولي أميد",
    "%82 Mikrofiber Polyamid": "82% بولي أميد ميكروفايبر",
    "%90 Bamboo": "90% بامبو",
    "%90 Bamcoo": "90% بامبو",
    "Beyaz ve Siyah renkleriyle": "بلونين أبيض وأسود",
    "Bölgesel baskıyla duble etkili şekillenme": "تشكيل مضاعف بضغط موضعي",
    "Bölgesel duble etki": "تأثير مضاعف موضعي",
    "Bölgesel duble şekillendirici etki": "تأثير تشكيل مضاعف موضعي",
    "Dolgun sünger": "حشوة مبطنة",
    "Doğal bamboo kumaş sayesinde ipeksi dokunuş": "ملمس حريري بفضل قماش البامبو الطبيعي",
    "Geliştirilmiş örgü sistemi": "نظام حياكة محسّن",
    "Göbeği kavrayan ergonomik kumaş": "قماش مريح يحتضن منطقة البطن",
    "Göbeği saran ergonomik örgü": "حياكة مريحة تلتف حول منطقة البطن",
    "Kaymayı önleyen çevre silikon": "حافة سيليكون مضادة للانزلاق",
    "Kolay kullanılabilen kopça": "مشبك سهل الاستخدام",
    "Kolay kullanım": "سهل الاستخدام",
    "Kolay çıkarılabilen ağraf": "إغلاق بخطاف سهل الفك",
    "LAZER KESİM, Pamuk ağ": "قص ليزر، جيب قطني",
    "LAZER kesim, özel dikiş": "قص ليزر، خياطة خاصة",
    "Lazer kesim, özel dikiş": "قص ليزر، خياطة خاصة",
    "Nefes alabilen doğal bamboo kumaş": "قماش بامبو طبيعي قابل للتنفس",
    "Nefes alabilen özel spor kumaş": "قماش رياضي تقني قابل للتنفس",
    "Organik kumaş": "قماش عضوي",
    "Organik, pratik kullanım": "عضوي، سهل الاستخدام",
    "Pamuk ağ": "جيب قطني",
    "Pamuk ağ, LAZER kesim iz yapmaz.": "جيب قطني، حواف مقصوصة بالليزر لا تترك أثرًا.",
    "Push up etkili": "تأثير رافع",
    "Rahat, konforu": "راحة مريحة",
    "Renk seçenekleri; Natural": "خيار اللون: طبيعي",
    "Renk; Siyah": "اللون: أسود",
    "S, M, L": "S, M, L",
    "S, M, L, XL  beden seçenekleri": "مقاسات S, M, L, XL",
    "S, M, L, XL ve XXL  beden seçenekleri": "مقاسات S, M, L, XL و XXL",
    "S, M, L, XL, XXL  ve 3XL beden seçenekleri": "مقاسات S, M, L, XL, XXL و 3XL",
    "S, M, L, XL, XXL ve 3XL  beden seçenekleri": "مقاسات S, M, L, XL, XXL و 3XL",
    "S-M-L-XL-XXL-3XL": "S-M-L-XL-XXL-3XL",
    "S/M,  M/L,  L/XL  beden seçenekleri": "مقاسات S/M, M/L, L/XL",
    "S/M, L/XL": "S/M, L/XL",
    "S/M, M/L, L/XL": "S/M, M/L, L/XL",
    "S/M, M/L. L/XL": "S/M, M/L, L/XL",
    "S/M. L/XL": "S/M, L/XL",
    "Sezon Renkleri ile": "بألوان موسمية",
    "Sezon Renkleri İle": "بألوان موسمية",
    "Siyah, Beyaz ve Ten renk alternatifi": "بديل الألوان أسود وأبيض وبيج",
    "Siyah, Beyaz, Ten ve sezon renkleriyle": "بألوان أسود وأبيض وبيج وألوان موسمية",
    "Siyah, Ekru ve Ten": "أسود وإكرو وبيج",
    "Siyah, Ten": "أسود، بيج",
    "Toparlatıcı ve şekillendirici etki": "تأثير شدّ وتشكيل",
    "Toparlayıcı etki": "تأثير شدّ",
    "Vucudu sarar": "يحتضن الجسم",
    "Vücudu saran korsajlı örgü": "حياكة مشدودة تحتضن الجسم",
    "Vücudu saran organik kumaş": "قماش عضوي يحتضن الجسم",
    "Vücudu sarar.": "يحتضن الجسم.",
    "XS/S,  M/L": "XS/S, M/L",
    "XS/S,  M/L,  L/XL": "XS/S, M/L, L/XL",
    "Yok hissi, iz yapmaz.": "إحساس بالخفة، لا يترك أثرًا.",
    "ipeksi dokunuş": "ملمس حريري",
    "iz yapmaz.": "لا يترك أثرًا.",
    "pamuk ağ, iz yapmaz.": "جيب قطني، لا يترك أثرًا.",
    "vücudu sarar.": "يحتضن الجسم.",
    "Çıkarılabilen sünger": "حشوة قابلة للإزالة",
    "Özel korsajlı örgü": "حياكة خاصة مشدودة",
    "İpeksi bamboo kumaş": "قماش بامبو حريري",
    "İpeksi doku": "نسيج حريري",
    "İz yapmayan özel dikiş": "خياطة خاصة لا تترك أثرًا",
    "İz yapmaz.": "لا يترك أثرًا.",
}

with open(SRC, encoding="utf-8") as f:
    products = json.load(f)

def build(cat_map, color_map, feat_map):
    out = []
    for p in products:
        out.append({
            **p,
            "categories": [cat_map.get(c, c) for c in p["categories"]],
            "colors": [color_map.get(c, c) for c in p["colors"]],
            "features": [feat_map.get(ft, ft) for ft in p["features"]],
        })
    return out

en = build(CAT_EN, COLOR_EN, FEATURE_EN)
ar = build(CAT_AR, COLOR_AR, FEATURE_AR)

with open("/Users/macos/ErgenTekstil/src/data/products.en.json", "w", encoding="utf-8") as f:
    json.dump(en, f, ensure_ascii=False, indent=2)
with open("/Users/macos/ErgenTekstil/src/data/products.ar.json", "w", encoding="utf-8") as f:
    json.dump(ar, f, ensure_ascii=False, indent=2)

# sanity: report any feature not translated
all_feats = set()
for p in products:
    all_feats.update(p["features"])
missing = [f for f in all_feats if f not in FEATURE_EN]
print("Çevrilmeyen özellik sayısı:", len(missing))
for m in missing:
    print(" -", m)
print("Tamam: products.en.json ve products.ar.json yazıldı")
